---
title: "Structural Equation Modelling of the World Happiness Report"
author: "Adejumo Ridwan Suleiman"
format: html
---

# Libraries
```{r}
library(tidyverse)
library(lavaan)
library(readxl)
library(psych)
```


# Data Loading and Cleaning
```{r}
# Load Data
whr <- read.csv("whr.csv")

# Rename variables
whr <- whr |> 
  rename(
    LL = Life.Ladder,
    GDP = Log.GDP.per.capita,
    SS = Social.support,
    LE = Healthy.life.expectancy.at.birth,
    FLC = Freedom.to.make.life.choices,
    GEN = Generosity,
    PC = Perceptions.of.corruption,
    PAF = Positive.affect,
    NAF = Negative.affect,
  ) |> 
  select(
    -c(1:2)
  )

skimr::skim(whr)
```


# Exploratory Data Analysis

# Factor Analysis
```{r}
# Establish two sets of indices to split the dataset
N <- nrow(whr)
indices <- seq(1, N)
indices_EFA <- sample(indices, floor((.5*N)))
indices_CFA <- indices[!(indices %in% indices_EFA)]

# Use indices to split dataset into half
whr_EFA <- whr[indices_EFA, ]
whr_CFA <- whr[indices_CFA, ]

# Use the indices  to create a grouping variable
group_var <- vector("numeric", nrow(whr))
group_var[indices_EFA] <- 1
group_var[indices_CFA] <- 2

# Bind that grouping variable onto the gcbs dataset
whr_grouped <- cbind(whr, group_var)

```

```{r}
# Calculate the correlation matrix 
whr_EFA_cor <- cor(whr_EFA, use = "pairwise.complete.obs")

# Then use that correlation matrix to calculate eigenvalues
eigenvals <- eigen(whr_EFA_cor)

# Look at the eigenvalues returned
eigenvals$values
```

```{r}
# scree plot
scree(whr_EFA_cor, factors = FALSE)
```

```{r}
# Run the EFA with three factors
EFA_model <- fa(whr_EFA, nfactors=3)

# View items' factor loadings
EFA_model$loadings
```


```{r}
summary(EFA_model)
```

# Structural Equation Modelling 

## Measurement Model
```{r}
mea_model_syntax = "
F1 =~ LL + GDP + LE
F2 =~ FLC + GEN + PAF + NAF
F3 =~ SS + PC 
HAPP =~ F1 + F2 + F3
"
mea_model <- sem(mea_model_syntax, data = whr_CFA)

summary(mea_model, fit.measures = TRUE, standardized = TRUE)

```


```{r}
modificationindices(str_model, sort. = TRUE)
```
## Structural Model
```{r}
str_model_syntax = "
F1 =~ LL + GDP + LE + FLC
F2 =~ FLC + GEN + PAF + NAF + LL
F3 =~ SS + PC + LE
HAPP =~ F1 + F2 + F3
NAF	~~	SS
FLC	~~	PC
LE	~~	FLC
GEN	~~	PC
GDP	~~	FLC
LE	~~	NAF
FLC	~~	GEN
"
str_model <- sem(str_model_syntax, data = whr_CFA)

summary(str_model, fit.measures = TRUE, standardized = TRUE)
```

